---
- hosts: all
  order: sorted
  gather_facts: false
  become: true
  roles:
  - tmout_set
  tags:
    - all

- hosts: missed
  order: sorted
  gather_facts: false
  become: true
  roles:
  - tmout_set
  tags:
    - missed
